### ISSUE TITLE
No longer work.

### ISSUE THREAD

**Issue by mikhoul** [jricardo27/AliexpressFullPrice#1]
No longer work.

**Comment by jricardo27** [comment]
Thanks for letting me know.

I updated it.

**Comment by mikhoul** [comment]
Thanks a lot for the update ! :+1:

**Comment by mikhoul** [comment]
Oups @jricardo27  could you upload it on Github since I don't see the update on Github right now.

![image](https://user-images.githubusercontent.com/5678673/193633742-e5d37a4d-4a5a-43dc-be20-2ff4ea29405d.png)

**Comment by mikhoul** [comment]
OK @jricardo27  I found the new version 1.2 in the Gist and tried it and for USD currency it seem to work fine but don't sort the price from lower to higher.

Also since I'm in Canada when my location is Canada and my currency is CAD it don't work at all.

![image](https://user-images.githubusercontent.com/5678673/193645308-c3bd20ce-42e6-499e-b6d7-222bb53f6b93.png)

![image](https://user-images.githubusercontent.com/5678673/193646377-7d760407-ce89-4ffd-82c8-a9b7d09f115f.png)




If you need more information to fix it just ask me ! 

Best Regard :octocat:
